/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateSwapPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "SWAP_FEE_BPS"
      | "addLiquidity"
      | "cancelCommitment"
      | "commitSwap"
      | "encReserve0"
      | "encReserve1"
      | "getAmountOut"
      | "getReserves"
      | "initialize"
      | "lastEncAmountOut"
      | "lastEncAmountOutOf"
      | "lastZeroForOne"
      | "lastZeroForOneOf"
      | "liquidityOf"
      | "owner"
      | "quoteAddLiquidity"
      | "quoteRemoveLiquidity"
      | "removeLiquidity"
      | "reserve0"
      | "reserve1"
      | "swap"
      | "swapCommitments"
      | "swapWithCommitment"
      | "token0"
      | "token1"
      | "totalLiquidity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "Swap"
      | "SwapCommitmentCancelled"
      | "SwapCommitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SWAP_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelCommitment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitSwap",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "encReserve0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "encReserve1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserves",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastEncAmountOut",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastEncAmountOutOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastZeroForOne",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastZeroForOneOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quoteAddLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteRemoveLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "reserve0", values?: undefined): string;
  encodeFunctionData(functionFragment: "reserve1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [BigNumberish, BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapCommitments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapWithCommitment",
    values: [BigNumberish, BigNumberish, boolean, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token0", values?: undefined): string;
  encodeFunctionData(functionFragment: "token1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalLiquidity",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SWAP_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commitSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "encReserve0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encReserve1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastEncAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastEncAmountOutOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastZeroForOne",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastZeroForOneOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteAddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteRemoveLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserve0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reserve1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapWithCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalLiquidity",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [reserve0: BigNumberish, reserve1: BigNumberish];
  export type OutputTuple = [reserve0: bigint, reserve1: bigint];
  export interface OutputObject {
    reserve0: bigint;
    reserve1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    provider: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    liquidity: BigNumberish,
    reserve0: BigNumberish,
    reserve1: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    amount0: bigint,
    amount1: bigint,
    liquidity: bigint,
    reserve0: bigint,
    reserve1: bigint
  ];
  export interface OutputObject {
    provider: string;
    amount0: bigint;
    amount1: bigint;
    liquidity: bigint;
    reserve0: bigint;
    reserve1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    provider: AddressLike,
    amount0: BigNumberish,
    amount1: BigNumberish,
    liquidity: BigNumberish,
    reserve0: BigNumberish,
    reserve1: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    amount0: bigint,
    amount1: bigint,
    liquidity: bigint,
    reserve0: bigint,
    reserve1: bigint
  ];
  export interface OutputObject {
    provider: string;
    amount0: bigint;
    amount1: bigint;
    liquidity: bigint;
    reserve0: bigint;
    reserve1: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    user: AddressLike,
    zeroForOne: boolean,
    amountIn: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    zeroForOne: boolean,
    amountIn: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    user: string;
    zeroForOne: boolean;
    amountIn: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapCommitmentCancelledEvent {
  export type InputTuple = [user: AddressLike, commitment: BytesLike];
  export type OutputTuple = [user: string, commitment: string];
  export interface OutputObject {
    user: string;
    commitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapCommittedEvent {
  export type InputTuple = [user: AddressLike, commitment: BytesLike];
  export type OutputTuple = [user: string, commitment: string];
  export interface OutputObject {
    user: string;
    commitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateSwapPool extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateSwapPool;
  waitForDeployment(): Promise<this>;

  interface: PrivateSwapPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  SWAP_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [
      amount0Desired: BigNumberish,
      amount1Desired: BigNumberish,
      minLiquidity: BigNumberish,
      deadline: BigNumberish
    ],
    [
      [bigint, bigint, bigint] & {
        amount0: bigint;
        amount1: bigint;
        liquidity: bigint;
      }
    ],
    "nonpayable"
  >;

  cancelCommitment: TypedContractMethod<[], [void], "nonpayable">;

  commitSwap: TypedContractMethod<
    [commitment: BytesLike],
    [void],
    "nonpayable"
  >;

  encReserve0: TypedContractMethod<[], [bigint], "view">;

  encReserve1: TypedContractMethod<[], [bigint], "view">;

  getAmountOut: TypedContractMethod<
    [amountIn: BigNumberish, zeroForOne: boolean],
    [bigint],
    "view"
  >;

  getReserves: TypedContractMethod<[], [[bigint, bigint]], "view">;

  initialize: TypedContractMethod<
    [amount0: BigNumberish, amount1: BigNumberish],
    [void],
    "nonpayable"
  >;

  lastEncAmountOut: TypedContractMethod<[], [bigint], "view">;

  lastEncAmountOutOf: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  lastZeroForOne: TypedContractMethod<[], [boolean], "view">;

  lastZeroForOneOf: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  liquidityOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  quoteAddLiquidity: TypedContractMethod<
    [amount0Desired: BigNumberish, amount1Desired: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amount0: bigint;
        amount1: bigint;
        liquidity: bigint;
      }
    ],
    "view"
  >;

  quoteRemoveLiquidity: TypedContractMethod<
    [liquidity: BigNumberish],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "view"
  >;

  removeLiquidity: TypedContractMethod<
    [
      liquidity: BigNumberish,
      minAmount0: BigNumberish,
      minAmount1: BigNumberish,
      deadline: BigNumberish
    ],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;

  reserve0: TypedContractMethod<[], [bigint], "view">;

  reserve1: TypedContractMethod<[], [bigint], "view">;

  swap: TypedContractMethod<
    [
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      zeroForOne: boolean,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  swapCommitments: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  swapWithCommitment: TypedContractMethod<
    [
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      zeroForOne: boolean,
      salt: BytesLike,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  token0: TypedContractMethod<[], [string], "view">;

  token1: TypedContractMethod<[], [string], "view">;

  totalLiquidity: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SWAP_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [
      amount0Desired: BigNumberish,
      amount1Desired: BigNumberish,
      minLiquidity: BigNumberish,
      deadline: BigNumberish
    ],
    [
      [bigint, bigint, bigint] & {
        amount0: bigint;
        amount1: bigint;
        liquidity: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelCommitment"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitSwap"
  ): TypedContractMethod<[commitment: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "encReserve0"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "encReserve1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAmountOut"
  ): TypedContractMethod<
    [amountIn: BigNumberish, zeroForOne: boolean],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserves"
  ): TypedContractMethod<[], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [amount0: BigNumberish, amount1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastEncAmountOut"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastEncAmountOutOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastZeroForOne"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastZeroForOneOf"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "liquidityOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quoteAddLiquidity"
  ): TypedContractMethod<
    [amount0Desired: BigNumberish, amount1Desired: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        amount0: bigint;
        amount1: bigint;
        liquidity: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteRemoveLiquidity"
  ): TypedContractMethod<
    [liquidity: BigNumberish],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<
    [
      liquidity: BigNumberish,
      minAmount0: BigNumberish,
      minAmount1: BigNumberish,
      deadline: BigNumberish
    ],
    [[bigint, bigint] & { amount0: bigint; amount1: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserve0"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserve1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "swap"
  ): TypedContractMethod<
    [
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      zeroForOne: boolean,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapCommitments"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "swapWithCommitment"
  ): TypedContractMethod<
    [
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      zeroForOne: boolean,
      salt: BytesLike,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token0"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;
  getEvent(
    key: "SwapCommitmentCancelled"
  ): TypedContractEvent<
    SwapCommitmentCancelledEvent.InputTuple,
    SwapCommitmentCancelledEvent.OutputTuple,
    SwapCommitmentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SwapCommitted"
  ): TypedContractEvent<
    SwapCommittedEvent.InputTuple,
    SwapCommittedEvent.OutputTuple,
    SwapCommittedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint256,uint256)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "LiquidityAdded(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "Swap(address,bool,uint256,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;

    "SwapCommitmentCancelled(address,bytes32)": TypedContractEvent<
      SwapCommitmentCancelledEvent.InputTuple,
      SwapCommitmentCancelledEvent.OutputTuple,
      SwapCommitmentCancelledEvent.OutputObject
    >;
    SwapCommitmentCancelled: TypedContractEvent<
      SwapCommitmentCancelledEvent.InputTuple,
      SwapCommitmentCancelledEvent.OutputTuple,
      SwapCommitmentCancelledEvent.OutputObject
    >;

    "SwapCommitted(address,bytes32)": TypedContractEvent<
      SwapCommittedEvent.InputTuple,
      SwapCommittedEvent.OutputTuple,
      SwapCommittedEvent.OutputObject
    >;
    SwapCommitted: TypedContractEvent<
      SwapCommittedEvent.InputTuple,
      SwapCommittedEvent.OutputTuple,
      SwapCommittedEvent.OutputObject
    >;
  };
}
