/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPermissionCustomIdValidator__factory } from "./IPermissionCustomIdValidator__factory";
export { MockPermissioned__factory } from "./MockPermissioned__factory";
