/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPermissionCustomIdValidator,
  IPermissionCustomIdValidatorInterface,
} from "../../../../@fhenixprotocol/cofhe-mock-contracts/Permissioned.sol/IPermissionCustomIdValidator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "issuer",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "disabled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPermissionCustomIdValidator__factory {
  static readonly abi = _abi;
  static createInterface(): IPermissionCustomIdValidatorInterface {
    return new Interface(_abi) as IPermissionCustomIdValidatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPermissionCustomIdValidator {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPermissionCustomIdValidator;
  }
}
