/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockTaskManagerSol from "./MockTaskManager.sol";
export type { mockTaskManagerSol };
import type * as permissionedSol from "./Permissioned.sol";
export type { permissionedSol };
export type { ACL } from "./ACL";
export type { MockCoFHE } from "./MockCoFHE";
export type { MockQueryDecrypter } from "./MockQueryDecrypter";
export type { MockZkVerifier } from "./MockZkVerifier";
export type { TestBed } from "./TestBed";
