/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPermissionCustomIdValidator } from "./IPermissionCustomIdValidator";
export type { MockPermissioned } from "./MockPermissioned";
