/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cofheContracts from "./cofhe-contracts";
export type { cofheContracts };
import type * as cofheMockContracts from "./cofhe-mock-contracts";
export type { cofheMockContracts };
